services:
  mona:
    container_name: mona
    image: ghcr.io/hyperion13th144m/phantom-mona:main
    environment:
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
    volumes:
      - ${SRC_DIR}:/src-dir
      - ${DATA_DIR}:/data-dir
      - ${LOG_DIR_MONA}:/var/log/mona
    tty: true
  
  panther:
    container_name: panther
    image: ghcr.io/hyperion13th144m/phantom-panther:main
    environment:
      ES_URL: http://es01:9200
      ES_USER: ${ES_USER}
      ES_PASSWORD: ${ES_PASSWORD}
      ES_INDEX: ${ES_INDEX}
      SQLITE_PATH: /extra-dir/${SQLITE_NAME}
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
    volumes:
      - ${DATA_DIR}:/data-dir
      - ${LOG_DIR_PANTHER}:/var/log/panther
      - ${EXTRA_DATA_DIR}:/extra-dir
    tty: true

  fox:
    container_name: fox
    image: ghcr.io/hyperion13th144m/phantom-fox:main
    environment:
      NODE_ENV: production
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
    volumes:
      - ${DATA_DIR}:/data-dir
      - ${LOG_DIR_FOX}:/var/log/fox

  joker:
    container_name: joker
    image: ghcr.io/hyperion13th144m/phantom-joker:main
    environment:
      NODE_ENV: production
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
      ES_URL: http://es01:9200
      ES_USER: ${ES_USER}
      ES_PASSWORD: ${ES_PASSWORD}
      ES_INDEX: ${ES_INDEX}
      NEXT_PUBLIC_IMAGE_BASE_URL: /images
      NEXT_PUBLIC_DOCUMENT_BASE_URL: /docs
      SQLITE_PATH: /extra-dir/${SQLITE_NAME}
    volumes:
      - ${LOG_DIR_JOKER}:/var/log/joker
      - ${DATA_DIR}:/data-dir
      - ${EXTRA_DATA_DIR}:/extra-dir

  es01:
    image: ghcr.io/hyperion13th144m/phantom-elasticsearch:main
    container_name: phantom-elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      network.host: 0.0.0.0
      ELASTIC_PASSWORD: ${ES_PASSWORD}
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: always

  nginx:
    image: ghcr.io/hyperion13th144m/phantom-nginx:main
    container_name: phantom-nginx
    volumes:
      - ${DATA_DIR}:/usr/share/nginx/html
    ports:
      - ${NGINX_PORT}:8080

volumes:
  es-data:
